eid: 0
hyperparameters:
  in_channels: 1
  learning_rate: 0.0001
  num_epochs: 1
  resize: 64
  test_batch_size: 1
  train_batch_size: 5
  val_batch_size: 1
nn: pretrained
results:
  accuracy: 0.0
  training_losses:
  - 2.375961
  validation_losses:
  - 2.278731
