name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install .

      - name: Check Format
        run: |
          ruff check .

      - name: Check Type
        run: |
          mypy .

      - name: Run tests
        run: |
          export NN_NUM_EPOCHS=1
          export NN_TRANSFORM_RESIZE=64
          export SAVE_PLOT=1
          export NN_TRAIN_BATCH_SIZE=1
          export NN_TEST_BATCH_SIZE=1
          export NN_VAL_BATCH_SIZE=1
          export IMAGE_FILES_PATH="test-resources/img"
          export XML_FILES_PATH="test-resources/xml"
          MODEL="pretrained"
          python3 main.py
